#!/usr/bin/env node

var optparse = require('./trello/optparse');

optparse.init('trello_client');
optparse.addOption('--auth', '-a', '进行用户信息验证');
optparse.addOption('--member', '-m', '获取成员信息');
optparse.addOption('--board', '-b', '获取版块信息');
optparse.addOption('--lists', '-l', '获取列表信息');
optparse.addOption('--card', '-c', '获取卡片信息');
optparse.addOption('--organization', '-o', '获取组织信息');
optparse.run(function(options, arguments) {
  var configFileName = __dirname + '/../config.json';
  if (options.auth) {
    var trello = require('./trello/trello');
    trello.init(configFileName);
    return trello.auth();
  }

  if (options.organization) {
    return require('./trello/org/init').run(
      configFileName, options, arguments
    );
  }

  if (options.board && arguments.length > 0) {
    return require('./trello/board/init').run(
      configFileName, options, arguments
    );
  }

  if (options.lists && arguments.length > 0) {
    return require('./trello/lists/init').run(
      configFileName, options, arguments
    );
  }

  optparse.print_help();
});
