#!/usr/bin/env python
#-*- coding:utf-8 -*-

def main():
  #解决python 2.x中中文以ascii编码的错误
  import sys
  if sys.version_info.major < 3:
    reload(sys)
    sys.setdefaultencoding('utf8')

  import optparse
  parser = optparse.OptionParser()
  parser.add_option(
    '--auth', '-a', action = 'store_true', help = '进行用户信息验证'
  )
  parser.add_option(
    '--member', '-m', action = 'store_true', help = '获取成员信息'
  )

  parser.add_option(
    '--organization', '-o', action = 'store_true', help = '获取组织信息'
  )
  options, arguments = parser.parse_args()

  import run

  if options.auth:
    return run.auth()

  if options.organization:
    if len(arguments) == 0:
      return run.printOrgList()
    elif options.member:
      return run.printOrgMembers(arguments[0])
    else:
      return run.printOrgInfo(arguments[0])

  print(parser.print_help())

if __name__ == '__main__':
  main()
