#!/usr/bin/env python
#-*- coding:utf-8 -*-

def main():
  #解决python 2.x中中文以ascii编码的错误
  import sys
  if sys.version_info.major < 3:
    reload(sys)
    sys.setdefaultencoding('utf8')

  import optparse
  p = optparse.OptionParser()
  p.add_option('--organization', '-o', help = '获取组织信息')

  options, arguments = p.parse_args()

  if len(arguments) > 0 and arguments[0].lower() == 'oauth':
    return oauth()

  if isNotGetOrgsList(options):
    pass
  else:
    printOrgList()

def isNotGetOrgsList(options):
  return options.organization

def oauth():
  from trello.oauth import Oauth
  oauth = Oauth(getConfigFileName())
  try:
    oauth.oauth()
  except:
    print('用户信息验证失败。')

def printOrgList():
  from trello import getOrgs
  orgs = getData(getOrgs)
  if orgs:
    for org in orgs:
      print(org['displayName'] + '（' + org['name'] + '）')

def getData(function):
  try:
    dataSet = function(getConfigFileName())
    return dataSet
  except:
    from os import path
    print(
      '数据获取失败：请检查您的网络是否正常。\n' +
      '如果网络正常请执行%s oauth进行用户信息验证'
      % path.abspath(__file__)
    )
    return None

def getConfigFileName():
  from os import path
  return path.abspath(__file__ + '/../../config.json')

if __name__ == '__main__':
  main()
